<!-- handle both success & failed scenarios - handle resolve & reject in asynchronous API-->
 <script>
    function getProducts(onSuccess){
      return new Promise((resolve, reject) => {   
        setTimeout(() =>  { 
            if(onSuccess){
                let products = [
                    {pid: 101, pname: 'Computer'},
                    {pid: 102, pname: 'Laptop'},
                    {pid: 103, pname: 'Mobile'},
                ]
                resolve(products);
            }else{
                reject('Products cannot be fetched')
            }
        }, 5000)});
		
    }
 </script>
 <script>
   // getProducts(true)
    getProducts(false)
        .then((products) => console.log(products))
        .catch((error) => console.error(error));
 </script>